media:
  - name: articles
    label: Статьи
    extensions: [md]
    input: articles
    output: articles
  - name: covers
    label: Обложки
    extensions: [png, jpg, webp, jpeg]
    input: images
    output: images
  - name: images
    label: Картинки для статей
    extensions: [png, jpg, webp, jpeg]
    input: articles/images
    output: images
    rename: safe
  - name: tournament-images
    label: Картинки для турниров
    extensions: [png, jpg, webp, jpeg]
    input: images
    output: ../../images
    rename: safe
  - name: tournaments
    label: Регламент турнира
    extensions: [md]
    input: tournaments
    output: /
  - name: rosters
    label: Ростеры
    extensions: [txt]
    input: tournaments
    output: rosters
content:
  - name: downloads
    label: Загрузки
    type: file
    path: data/downloads.json
    format: json
    list: true
    fields:
      - name: slug
        type: string
        required: true
        label: Идентификатор
        pattern:
          regex: ^[a-z0-9]+(?:-[a-z0-9]+)*$
          message: "Некорректный формат slug. Используйте только латинские буквы, цифры и дефисы."
      - name: title
        label: Название
        type: string
        required: true
      - name: description
        label: Описание
        type: string
        required: true
      - name: category
        label: Категория
        type: string
        required: true
      - name: driveLink
        label: Ссылка на файл
        type: string
        required: true
      - name: date
        type: date
        label: Дата публикации
        options:
          format: "yyyy-MM-dd"
        required: true
  - name: calendar
    label: Календарь Ивентов
    type: file
    path: data/events.json
    format: json
    list: true
    fields:
      - name: title
        label: Название
        type: string
        required: true
        description: "Название ивента"
      - name: date
        label: Дата
        type: date
        required: true
        description: "Дата проведения"
        options:
          format: "yyyy-MM-dd"
      - name: category
        label: Категория
        type: select
        required: true
        description: "Категория ивента"
        options:
          values: ["Турнир", "Открытый день", "Игродень", "Хобби-день", "Мастер-класс"]
      - name: location
        label: Место
        type: string
        required: true
        description: "Место проведения ивента"
      - name: organizer
        label: Организатор
        type: string
        required: true
        description: "Организатор ивента"
      - name: url
        label: Ссылка
        type: string
        description: "Ссылка на страницу ивента (должна быть заранее опубликована)."
  - name: Articles
    label: Статьи и Новости
    type: group
    items:
      - name: text
        label: Тексты статей
        type: collection
        path: articles
        subfolders: true
        view:
          fields: [title, author, date]
        fields:
          - name: title
            label: Название
            type: string
          - name: author
            label: Автор
            type: string
          - name: date
            label: Дата
            type: date
          - name: body
            type: rich-text
            options:
              media: images
      - name: metadata
        label: Метаданные статей
        type: file
        path: data/articles.json
        format: json
        list: true
        fields:
          - name: slug
            type: string
            required: true
            label: Идентификатор статьи (slug)
            description: "Используется в адресе страницы. Только латинские буквы в нижнем регистре, цифры и дефисы."
            pattern:
              regex: ^[a-z0-9]+(?:-[a-z0-9]+)*$
              message: "Некорректный формат slug. Используйте только латинские буквы, цифры и дефисы."
          - name: title
            label: Заголовок статьи
            description: "Название статьи, которое будет отображаться на странице и в списках материалов."
            type: string
            required: true
          - name: excerpt
            type: string
            label: Краткое описание
            description: "Небольшое описание статьи для превью и списка материалов."
          - name: tags
            label: Теги
            description: "Выберите категории, которые описывают статью. Можно выбрать несколько. Для попадания статьи в раздел \"новости\" у нее должен быть тег \"новость\"."
            type: select
            options:
              multiple: true
              values: ["новость", "гайд", "новичкам", "лор", "правила", "перевод", "репорт", "фото"]
              min: 1
            required: true
          - name: date
            type: date
            label: Дата публикации
            description: "Дата, которая будет отображаться как дата выхода статьи."
            options:
              format: "yyyy-MM-dd"
            required: true
          - name: author
            type: string
            label: Автор
            description: "Имя автора или название команды, разместившей материал."
            required: true
          - name: cover
            type: file
            label: "Картинка для обложки"
            options:
              media: covers
              rename: safe
          - name: mdFile
            type: file
            label: Файл статьи (Markdown)
            description: "Путь к файлу с текстом статьи в формате Markdown. Например: articles/news/my-article.md"
            required: true
            options:
              media: articles
  - name: tournaments
    label: Турниры
    type: group
    items:
      - name: rules
        label: Регламенты
        type: collection
        path: tournaments
        subfolders: true
        view:
          fields: [title, organizer, date]
        fields:
          - name: title
            label: Название
            type: string
          - name: organizer
            label: Организатор
            type: string
          - name: date
            label: Дата
            type: date
          - name: body
            type: rich-text
            options:
              media: tournament-images
      - name: tournaments-metadata
        label: Метаданные турниров
        type: file
        path: data/tournaments.json
        format: json
        list: true
        fields:
          - name: slug
            type: string
            required: true
            label: Идентификатор турнира (slug)
            description: "Используется в адресе страницы. Только латинские буквы в нижнем регистре, цифры и дефисы."
            options:
              regex: ^[a-z0-9]+(?:-[a-z0-9]+)*$
              message: "Некорректный формат slug. Используйте только латинские буквы, цифры и дефисы."
          - name: name
            label: Название турнира
            description: "Название турнира, которое будет отображаться на странице и в календаре ивентов."
            type: string
            required: true
          - name: date
            type: date
            label: Дата
            description: "Дата проведения турнира."
            options:
              format: "yyyy-MM-dd"
            required: true
          - name: location
            label: Место
            description: "Место проведения турнира."
            type: string
            required: true
          - name: organizer
            label: Организатор
            type: string
            required: true
            description: "Организатор турнира"
          - name: finished
            label: Статус
            description: "Активируйте, если турнир уже прошел. Если активировано, карточка турниров попадет в раздел \"Архив\" на старнице турниров, а на странице самого турнира отобразится таблица результатов."
            type: boolean
            default: false
            required: true
          - name: rulesLink
            label: Ссылка на регламент
            type: string
            description: "Ссылка на регламент, опубликованный на стороннем ресурсе. Необязательное поле."
          - name: rulesFile
            label: Регламент
            description: "Регламент для публикации на странице турнира. Заменяет ссылку на регламент."
            type: file
            options:
              media: tournaments
          - name: players
            label: Участники
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{index} ({name})"
            fields:
              - name: name
                label: Имя
                type: string
              - name: army
                label: Фракция
                type: string
              - name: rosterFile
                label: Ростер
                type: string
                description: "Используйте \"rosters/<roster_file_name>.txt\""
              - name: wins
                label: Победы
                type: number
                options:
                  min: 0
                  max: 5
              - name: losses
                label: Поражения
                type: number
                options:
                  min: 0
                  max: 5
              - name: draws
                label: Ничьи
                type: number
                options:
                  min: 0
                  max: 5
              - name: points
                label: Очки
                type: number
                options:
                  min: 0