media:
  - name: articles_images
    label: Articles
    rename: safe
    extensions: [png, jpg, webp, jpeg]
    input: images
    output: images/articles
    actions:
      - name: optimize-images
        label: Optimize images
        workflow: pages-cms-media-action.yml
content:
  - name: News
    label: News
    type: collection
    path: articles/news
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text